name: flutter

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
      - name: Linter
        run: flutter analyze
  analysis_min_sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: subosito/flutter-action@v2.12.0
        with:
          cache: true
          flutter-version: '3.27'
          channel: 'stable'
      - name: Version
        run: flutter doctor -v
      - name: Install dependencies
        run: flutter pub get
      - name: Linter
        run: flutter analyze
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          # TODO: move the code to the new tall style once Flutter 3.29 is the new minimum.
          # https://github.com/juliansteenbakker/mobile_scanner/issues/1326
          flutter-version: '3.27'
      - name: Format
        run: dart format --set-exit-if-changed .